version: "3.9"

services:
  app:
    build: .
    container_name: sekolah_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sekolah_db
    environment:
      MYSQL_ROOT_PASSWORD: rahasia
      MYSQL_DATABASE: sekolah
      MYSQL_USER: sekolah
      MYSQL_PASSWORD: rahasia
    ports:
      - "3306:3306"
